spring:
  application:
    name: triphub
  profiles:
    active: dev  # Change to 'prod' when deploying to production

api:
  base:
    path: api/v1

#fronted cors
application:
  frontend-urls: "http://localhost:3000, https://your-production-frontend.com"

jwt:
  access-token-validity-ms: 900000     # 15 minutes in ms
  refresh-token-validity-ms: 604800000 # 7 days in ms

springdoc:
  swagger-ui:
    path: /api-docs.html
