spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://<PROD_HOST>:5432/triphub
    username: <PROD_USER>
    password: <PROD_PASSWORD>
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

